import './globals.css'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// app/layout.tsx
import { Providers } from "./providers";
import Header from './Components/Navigation';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div id='root'></div>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
